//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_H
#define METASPRITE_font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_TILE_ORIGIN 0
#define font_TILE_H 8
#define font_WIDTH 208
#define font_HEIGHT 16
#define font_TILE_COUNT 45
#define font_PALETTE_COUNT 1
#define font_MAP_ATTRIBUTES 0
#define font_TILE_PALS font_tile_pals

BANKREF_EXTERN(font)

extern const palette_color_t font_palettes[4];
extern const uint8_t font_tiles[720];

extern const unsigned char font_map[52];
extern const unsigned char* font_tile_pals[45];

#endif