//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_mario_H
#define METASPRITE_mario_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define mario_TILE_ORIGIN 0
#define mario_TILE_H 16
#define mario_WIDTH 16
#define mario_HEIGHT 32
#define mario_TILE_COUNT 24
#define mario_PALETTE_COUNT 1
#define mario_PIVOT_X 8
#define mario_PIVOT_Y 16
#define mario_PIVOT_W 16
#define mario_PIVOT_H 32

BANKREF_EXTERN(mario)

extern const palette_color_t mario_palettes[4];
extern const uint8_t mario_tiles[384];

extern const metasprite_t* const mario_metasprites[5];

#endif