//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_mushroom_H
#define METASPRITE_mushroom_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define mushroom_TILE_ORIGIN 0
#define mushroom_TILE_H 16
#define mushroom_WIDTH 16
#define mushroom_HEIGHT 16
#define mushroom_TILE_COUNT 4
#define mushroom_PALETTE_COUNT 1
#define mushroom_PIVOT_X 8
#define mushroom_PIVOT_Y 8
#define mushroom_PIVOT_W 16
#define mushroom_PIVOT_H 16

BANKREF_EXTERN(mushroom)

extern const palette_color_t mushroom_palettes[4];
extern const uint8_t mushroom_tiles[64];

extern const metasprite_t* const mushroom_metasprites[1];

#endif